<?php

declare(strict_types=1);

namespace LaraMint\LaravelBrain\OpenApi;

use LaraMint\LaravelBrain\Analysis\ControllerDefinition;
use LaraMint\LaravelBrain\Analysis\RouteDefinition;
use LaraMint\LaravelBrain\Analysis\ValidationRulesExtractor;

/**
 * Converts the route + controller analysis output into an OpenAPI 3.0.3 document.
 *
 * Pure transformer — does no AST parsing itself beyond delegating FormRequest
 * inspection to ValidationRulesExtractor.
 */
final class OpenApiBuilder
{
    private ValidationRulesExtractor $rulesExtractor;

    private LaravelRuleConverter $ruleConverter;

    public function __construct(?ValidationRulesExtractor $rulesExtractor = null, ?LaravelRuleConverter $ruleConverter = null)
    {
        $this->rulesExtractor = $rulesExtractor ?? new ValidationRulesExtractor;
        $this->ruleConverter = $ruleConverter ?? new LaravelRuleConverter;
    }

    /**
     * @param  RouteDefinition[]  $routes
     * @param  array<string, ControllerDefinition>  $controllers  FQCN => def
     * @return array<string, mixed>
     */
    public function build(array $routes, array $controllers, string $title = 'Laravel API', string $version = '1.0.0'): array
    {
        $paths = [];
        $securitySchemes = [];

        foreach ($routes as $route) {
            $pathKey = $this->normaliseUri($route->uri);
            $methodKey = strtolower($route->method);

            $operation = $this->buildOperation($route, $controllers, $securitySchemes);

            if (! isset($paths[$pathKey])) {
                $paths[$pathKey] = [];
            }
            $paths[$pathKey][$methodKey] = $operation;
        }

        $spec = [
            'openapi' => '3.0.3',
            'info' => [
                'title' => $title,
                'version' => $version,
                'description' => 'Generated by Laravel Brain.',
            ],
            'paths' => $paths,
        ];

        if ($securitySchemes !== []) {
            $spec['components'] = ['securitySchemes' => $securitySchemes];
        }

        return $spec;
    }

    /**
     * @param  array<string, ControllerDefinition>  $controllers
     * @param  array<string, array<string, mixed>>  $securitySchemes  collected by reference
     * @return array<string, mixed>
     */
    private function buildOperation(RouteDefinition $route, array $controllers, array &$securitySchemes): array
    {
        $operation = [
            'operationId' => $route->name !== '' ? $route->name : $this->fallbackOperationId($route),
            'summary' => $route->name !== '' ? $route->name : ($route->controller.'@'.$route->action),
            'tags' => [$this->tagFor($route)],
            'parameters' => $this->buildPathParameters($route->uri),
        ];

        $security = $this->buildSecurity($route->middlewares, $securitySchemes);
        if ($security !== []) {
            $operation['security'] = $security;
        }

        if (in_array(strtolower($route->method), ['post', 'put', 'patch'], true)) {
            $requestBody = $this->buildRequestBody($route, $controllers);
            if ($requestBody !== null) {
                $operation['requestBody'] = $requestBody;
            }
        }

        $operation['responses'] = [
            '200' => ['description' => 'OK'],
        ];

        return $operation;
    }

    private function fallbackOperationId(RouteDefinition $route): string
    {
        $slug = preg_replace('#[^A-Za-z0-9]+#', '_', $route->uri) ?? '';
        $slug = trim($slug, '_');

        return strtolower($route->method).'_'.($slug !== '' ? $slug : 'root');
    }

    private function tagFor(RouteDefinition $route): string
    {
        if ($route->controller === '' || $route->controller === 'Closure') {
            return 'closures';
        }

        $short = ltrim(strrchr('\\'.$route->controller, '\\') ?: $route->controller, '\\');

        return preg_replace('/Controller$/', '', $short) ?: $short;
    }

    private function normaliseUri(string $uri): string
    {
        $uri = '/'.ltrim($uri, '/');

        // Laravel optional params {param?} → {param}
        return preg_replace('/\{([^}?]+)\?\}/', '{$1}', $uri) ?? $uri;
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function buildPathParameters(string $uri): array
    {
        preg_match_all('/\{([^}]+)\}/', $uri, $matches);
        $params = [];
        foreach ($matches[1] as $raw) {
            $optional = str_ends_with($raw, '?');
            $name = rtrim($raw, '?');
            $params[] = [
                'name' => $name,
                'in' => 'path',
                'required' => ! $optional,
                'schema' => ['type' => 'string'],
            ];
        }

        return $params;
    }

    /**
     * @param  array<string, ControllerDefinition>  $controllers
     * @return array<string, mixed>|null
     */
    private function buildRequestBody(RouteDefinition $route, array $controllers): ?array
    {
        $controller = $controllers[$route->controller] ?? null;
        if ($controller === null) {
            return null;
        }

        $method = null;
        foreach ($controller->methods as $m) {
            if ($m->name === $route->action) {
                $method = $m;
                break;
            }
        }
        if ($method === null) {
            return null;
        }

        $formRequestFqcn = $this->detectFormRequest($method->dependencies);
        if ($formRequestFqcn === null) {
            return null;
        }

        $file = $this->resolveFormRequestFile($formRequestFqcn, $controller);
        if ($file === null || ! is_file($file)) {
            return null;
        }

        $rows = $this->rulesExtractor->extractFromFile($file);
        if ($rows === []) {
            return null;
        }

        $properties = [];
        $required = [];

        foreach ($rows as $row) {
            $field = trim($row['field'], "'\"");
            if ($field === '' || $field === '*') {
                continue;
            }
            $converted = $this->ruleConverter->convert($row['rules']);
            $properties[$field] = $converted['schema'];
            if ($converted['required']) {
                $required[] = $field;
            }
        }

        if ($properties === []) {
            return null;
        }

        $schema = [
            'type' => 'object',
            'properties' => $properties,
        ];
        if ($required !== []) {
            $schema['required'] = $required;
        }

        return [
            'required' => $required !== [],
            'content' => [
                'application/json' => ['schema' => $schema],
            ],
        ];
    }

    /**
     * @param  array<string, string>  $dependencies  varName => FQCN
     */
    private function detectFormRequest(array $dependencies): ?string
    {
        foreach ($dependencies as $fqcn) {
            if ($fqcn === '' || $fqcn === 'Illuminate\\Http\\Request') {
                continue;
            }
            // Convention: Laravel FormRequests live under *\Http\Requests\* or end with "Request"
            if (preg_match('#\\\\Http\\\\Requests\\\\#', $fqcn)
                || preg_match('#Request$#', $fqcn) === 1
            ) {
                return $fqcn;
            }
        }

        return null;
    }

    private function resolveFormRequestFile(string $fqcn, ControllerDefinition $controller): ?string
    {
        // Try PSR-4 derivation relative to the controller file's project root.
        $controllerFile = $controller->file;
        if ($controllerFile === '' || ! is_file($controllerFile)) {
            return null;
        }

        // Walk up from controller file looking for app/Http/Requests/<...>.php matching the FQCN.
        $relativeClass = str_replace('\\', '/', $fqcn).'.php';
        $dir = dirname($controllerFile);
        for ($i = 0; $i < 8 && $dir !== '/' && $dir !== '.'; $i++) {
            // Common Laravel layout: app/<...>/Foo.php where FQCN = App\<...>\Foo
            foreach (['app', 'src'] as $appDir) {
                $candidate = $dir.'/'.$appDir.'/'.preg_replace('#^App/#', '', $relativeClass);
                if (is_file($candidate)) {
                    return $candidate;
                }
            }
            $dir = dirname($dir);
        }

        return null;
    }

    /**
     * @param  string[]  $middlewares
     * @param  array<string, array<string, mixed>>  $securitySchemes  collected by reference
     * @return list<array<string, list<string>>>
     */
    private function buildSecurity(array $middlewares, array &$securitySchemes): array
    {
        $out = [];

        foreach ($middlewares as $mw) {
            if ($mw === 'auth' || str_starts_with($mw, 'auth:')) {
                $guard = str_starts_with($mw, 'auth:') ? substr($mw, 5) : 'web';
                if ($guard === 'sanctum' || $guard === 'api') {
                    $securitySchemes['bearerAuth'] = [
                        'type' => 'http',
                        'scheme' => 'bearer',
                    ];
                    $out[] = ['bearerAuth' => []];
                } else {
                    $securitySchemes['sessionAuth'] = [
                        'type' => 'apiKey',
                        'in' => 'cookie',
                        'name' => 'laravel_session',
                    ];
                    $out[] = ['sessionAuth' => []];
                }
            }
        }

        return $out;
    }
}
